version: '3'
services:
  postgres-db-demo-rest-api:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=demo-rest-api
      - POSTGRES_USER=demo-rest-api
      - POSTGRES_PASSWORD=secret-pass
    ports:
      - "35432:5432"