POST http://localhost:8080/api/v1/author
Content-Type: application/json

{
  "firstName": "Henryk",
  "lastName": "Sienkiewicz",
  "dateOfBirth": "1990-10-05",
  "localDescriptor": [
    {
      "sourceSystem": "open-library",
      "localIdentifier": "auth1"
    }
  ]
}

###
